package igu;

import javax.swing.JOptionPane;
import logica.Controladora;

/**
 *
 * @author Bimbo
 */
public class Principal extends javax.swing.JFrame {

    Controladora control;

    /**
     * Creates new form Principal
     */
    public Principal(Controladora controlRec) {
        control = controlRec;
        initComponents();
    }

    private void limpiar(){
        txtNombreDuenio.setText("Ingrese nombre Dueño");
        txtCelDuenio.setText("Ingrese celular Dueño");
        txtNombreMascota.setText("Ingrese nombre Mascota");
        txtRaza.setText("Ingrese raza Mascota");
        txtColor.setText("Ingrese color de Mascota");
        txtAreaTareas.setText("Ingrese las tareas realizadas y las observaciones");
        cmboxAlergico.setSelectedIndex(0);
        cmboxAtenEspecial.setSelectedIndex(0);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelTrabajo = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        panelCliente = new javax.swing.JPanel();
        lblNombreDuenio = new javax.swing.JLabel();
        lblCelularDuenio = new javax.swing.JLabel();
        txtCelDuenio = new javax.swing.JTextField();
        txtNombreDuenio = new javax.swing.JTextField();
        lblLogoCliente = new javax.swing.JLabel();
        lblNombreMascota = new javax.swing.JLabel();
        txtNombreMascota = new javax.swing.JTextField();
        lblRaza = new javax.swing.JLabel();
        txtRaza = new javax.swing.JTextField();
        lblColor = new javax.swing.JLabel();
        txtColor = new javax.swing.JTextField();
        lblMascota = new javax.swing.JLabel();
        lblAlergico = new javax.swing.JLabel();
        cmboxAlergico = new javax.swing.JComboBox<>();
        lblAtenEspecial = new javax.swing.JLabel();
        cmboxAtenEspecial = new javax.swing.JComboBox<>();
        logoTituloMascota = new javax.swing.JLabel();
        lblObservaciones = new javax.swing.JLabel();
        scrPanelTareas = new javax.swing.JScrollPane();
        txtAreaTareas = new javax.swing.JTextArea();
        panelLogo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Carga de Servicios");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelTrabajo.setBackground(new java.awt.Color(93, 184, 214));

        btnGuardar.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/patita 2.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/patita 5.png"))); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnSalir.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/patita 6.png"))); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTrabajoLayout = new javax.swing.GroupLayout(panelTrabajo);
        panelTrabajo.setLayout(panelTrabajoLayout);
        panelTrabajoLayout.setHorizontalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnLimpiar)
                .addGap(225, 225, 225)
                .addComponent(btnGuardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 239, Short.MAX_VALUE)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        panelTrabajoLayout.setVerticalGroup(
            panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTrabajoLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(panelTrabajoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnSalir))
                .addGap(24, 24, 24))
        );

        jPanel1.add(panelTrabajo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 630, 860, 90));

        panelCliente.setBackground(new java.awt.Color(94, 184, 214));

        lblNombreDuenio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombreDuenio.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreDuenio.setText("Nombre:");

        lblCelularDuenio.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblCelularDuenio.setForeground(new java.awt.Color(255, 255, 255));
        lblCelularDuenio.setText("Celular:");

        txtCelDuenio.setText("Ingrese celular Dueño");
        txtCelDuenio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCelDuenioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCelDuenioFocusLost(evt);
            }
        });

        txtNombreDuenio.setText("Ingrese nombre Dueño");
        txtNombreDuenio.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreDuenioFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreDuenioFocusLost(evt);
            }
        });

        lblLogoCliente.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        lblLogoCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblLogoCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/usuario.png"))); // NOI18N
        lblLogoCliente.setText(" Cliente");

        lblNombreMascota.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblNombreMascota.setForeground(new java.awt.Color(255, 255, 255));
        lblNombreMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/patita 1.png"))); // NOI18N
        lblNombreMascota.setText("Nombre: ");

        txtNombreMascota.setText("Ingrese nombre Mascota");
        txtNombreMascota.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtNombreMascotaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtNombreMascotaFocusLost(evt);
            }
        });

        lblRaza.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblRaza.setForeground(new java.awt.Color(255, 255, 255));
        lblRaza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/patita 3.png"))); // NOI18N
        lblRaza.setText("Raza:");

        txtRaza.setText("Ingrese raza Mascota");
        txtRaza.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRazaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRazaFocusLost(evt);
            }
        });

        lblColor.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblColor.setForeground(new java.awt.Color(255, 255, 255));
        lblColor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/patita 4.png"))); // NOI18N
        lblColor.setText("Color: ");

        txtColor.setText("Ingrese color de Mascota");
        txtColor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtColorFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtColorFocusLost(evt);
            }
        });

        lblMascota.setFont(new java.awt.Font("Lucida Sans", 1, 36)); // NOI18N
        lblMascota.setForeground(new java.awt.Color(255, 255, 255));
        lblMascota.setText("Mascota");

        lblAlergico.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAlergico.setForeground(new java.awt.Color(255, 255, 255));
        lblAlergico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/patita 7.png"))); // NOI18N
        lblAlergico.setText("Alergico:");

        cmboxAlergico.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Si" }));

        lblAtenEspecial.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblAtenEspecial.setForeground(new java.awt.Color(255, 255, 255));
        lblAtenEspecial.setText("Atención Especial: ");

        cmboxAtenEspecial.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Si" }));

        logoTituloMascota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/perrito.png"))); // NOI18N

        lblObservaciones.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblObservaciones.setForeground(new java.awt.Color(255, 255, 255));
        lblObservaciones.setText("Tareas / Observaciones:");

        txtAreaTareas.setColumns(20);
        txtAreaTareas.setRows(5);
        txtAreaTareas.setText("Ingrese las tareas realizadas y las observaciones");
        txtAreaTareas.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtAreaTareasFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtAreaTareasFocusLost(evt);
            }
        });
        scrPanelTareas.setViewportView(txtAreaTareas);

        javax.swing.GroupLayout panelClienteLayout = new javax.swing.GroupLayout(panelCliente);
        panelCliente.setLayout(panelClienteLayout);
        panelClienteLayout.setHorizontalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteLayout.createSequentialGroup()
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelClienteLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelClienteLayout.createSequentialGroup()
                                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblCelularDuenio)
                                    .addComponent(lblNombreDuenio))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNombreDuenio)
                                    .addComponent(txtCelDuenio, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panelClienteLayout.createSequentialGroup()
                                .addGap(94, 94, 94)
                                .addComponent(lblMascota)
                                .addGap(0, 103, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelClienteLayout.createSequentialGroup()
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelClienteLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lblObservaciones))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelClienteLayout.createSequentialGroup()
                                .addGap(118, 118, 118)
                                .addComponent(lblLogoCliente)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelClienteLayout.createSequentialGroup()
                                .addComponent(lblColor)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtColor))
                            .addGroup(panelClienteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(scrPanelTareas, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panelClienteLayout.createSequentialGroup()
                                        .addComponent(lblNombreMascota)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panelClienteLayout.createSequentialGroup()
                                        .addComponent(lblRaza)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(14, 14, 14)))
                .addGap(35, 35, 35))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAlergico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmboxAlergico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(150, 150, 150))
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(logoTituloMascota))
                    .addGroup(panelClienteLayout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(lblAtenEspecial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmboxAtenEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelClienteLayout.setVerticalGroup(
            panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLogoCliente)
                .addGap(18, 18, 18)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreDuenio)
                    .addComponent(txtNombreDuenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCelularDuenio)
                    .addComponent(txtCelDuenio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(logoTituloMascota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMascota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreMascota)
                    .addComponent(txtNombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRaza)
                    .addComponent(txtRaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblColor)
                    .addComponent(txtColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmboxAlergico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAlergico))
                .addGap(25, 25, 25)
                .addGroup(panelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAtenEspecial)
                    .addComponent(cmboxAtenEspecial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblObservaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrPanelTareas, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE))
        );

        jPanel1.add(panelCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 630));

        panelLogo.setBackground(new java.awt.Color(0, 71, 118));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagen/logo.png"))); // NOI18N

        javax.swing.GroupLayout panelLogoLayout = new javax.swing.GroupLayout(panelLogo);
        panelLogo.setLayout(panelLogoLayout);
        panelLogoLayout.setHorizontalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLogoLayout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(lblLogo))
        );
        panelLogoLayout.setVerticalGroup(
            panelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogoLayout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(lblLogo)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        jPanel1.add(panelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 440, 630));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // Metodo para salir de la aplicación
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // Coloca todos los campos con los textos originales.
        limpiar();
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txtNombreDuenioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreDuenioFocusGained
        // TODO add your handling code here:
        if (txtNombreDuenio.getText().equals("Ingrese nombre Dueño")) {
            txtNombreDuenio.setText("");
        }
    }//GEN-LAST:event_txtNombreDuenioFocusGained

    private void txtNombreDuenioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreDuenioFocusLost
        // TODO add your handling code here:
        if (txtNombreDuenio.getText().equals("")) {
            txtNombreDuenio.setText("Ingrese nombre Dueño");
        }
    }//GEN-LAST:event_txtNombreDuenioFocusLost

    private void txtCelDuenioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelDuenioFocusGained
        // TODO add your handling code here:
        if (txtCelDuenio.getText().equals("Ingrese celular Dueño")) {
            txtCelDuenio.setText("");
        }        
    }//GEN-LAST:event_txtCelDuenioFocusGained

    private void txtCelDuenioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCelDuenioFocusLost
        // TODO add your handling code here:
        if (txtCelDuenio.getText().equals("")) {
            txtCelDuenio.setText("Ingrese celular Dueño");
        }
    }//GEN-LAST:event_txtCelDuenioFocusLost

    private void txtNombreMascotaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreMascotaFocusGained
        // TODO add your handling code here:
        if (txtNombreMascota.getText().equals("Ingrese nombre Mascota")) {
            txtNombreMascota.setText("");
        }
    }//GEN-LAST:event_txtNombreMascotaFocusGained

    private void txtNombreMascotaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtNombreMascotaFocusLost
        // TODO add your handling code here:
        if (txtNombreMascota.getText().equals("")) {
            txtNombreMascota.setText("Ingrese nombre Mascota");
        }
    }//GEN-LAST:event_txtNombreMascotaFocusLost

    private void txtRazaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRazaFocusGained
        // TODO add your handling code here:
        if (txtRaza.getText().equals("Ingrese raza Mascota")) {
            txtRaza.setText("");
        }        
    }//GEN-LAST:event_txtRazaFocusGained

    private void txtRazaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRazaFocusLost
        // TODO add your handling code here:
        if (txtRaza.getText().equals("")) {
            txtRaza.setText("Ingrese raza Mascota");
        }
    }//GEN-LAST:event_txtRazaFocusLost

    private void txtColorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColorFocusGained
        // TODO add your handling code here:
        if (txtColor.getText().equals("Ingrese color de Mascota")) {
            txtColor.setText("");
        }        
    }//GEN-LAST:event_txtColorFocusGained

    private void txtColorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtColorFocusLost
        // TODO add your handling code here:
        if (txtColor.getText().equals("")) {
            txtColor.setText("Ingrese color de Mascota");
        }
    }//GEN-LAST:event_txtColorFocusLost

    private void txtAreaTareasFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAreaTareasFocusGained
        // TODO add your handling code here:
        if (txtAreaTareas.getText().equals("Ingrese las tareas realizadas y las observaciones")) {
            txtAreaTareas.setText("");
        }        
    }//GEN-LAST:event_txtAreaTareasFocusGained

    private void txtAreaTareasFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtAreaTareasFocusLost
        // TODO add your handling code here:
        if (txtAreaTareas.getText().equals("")) {
            txtAreaTareas.setText("Ingrese las tareas realizadas y las observaciones");
        }
    }//GEN-LAST:event_txtAreaTareasFocusLost

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // Guardar Servicio/Cliente/Mascota
        String nombreCliente=txtNombreDuenio.getText();
        String celCliente=txtCelDuenio.getText();
        String nombreMascota=txtNombreMascota.getText();
        String raza=txtRaza.getText();
        String color=txtColor.getText();
        String tareasObservaciones=txtAreaTareas.getText();        
        int alergico=cmboxAlergico.getSelectedIndex();
        int atencionEspecial=cmboxAtenEspecial.getSelectedIndex();
        try {
            control.guardarServicio(nombreCliente, celCliente, nombreMascota, raza, color, tareasObservaciones, alergico, atencionEspecial);
            JOptionPane.showMessageDialog(panelCliente, "Servicio guardado", "Guardar", JOptionPane.INFORMATION_MESSAGE);
            limpiar();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(panelCliente, e.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmboxAlergico;
    private javax.swing.JComboBox<String> cmboxAtenEspecial;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAlergico;
    private javax.swing.JLabel lblAtenEspecial;
    private javax.swing.JLabel lblCelularDuenio;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogoCliente;
    private javax.swing.JLabel lblMascota;
    private javax.swing.JLabel lblNombreDuenio;
    private javax.swing.JLabel lblNombreMascota;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JLabel logoTituloMascota;
    private javax.swing.JPanel panelCliente;
    private javax.swing.JPanel panelLogo;
    private javax.swing.JPanel panelTrabajo;
    private javax.swing.JScrollPane scrPanelTareas;
    private javax.swing.JTextArea txtAreaTareas;
    private javax.swing.JTextField txtCelDuenio;
    private javax.swing.JTextField txtColor;
    private javax.swing.JTextField txtNombreDuenio;
    private javax.swing.JTextField txtNombreMascota;
    private javax.swing.JTextField txtRaza;
    // End of variables declaration//GEN-END:variables
}
